server:
  port: ${PORT:8070}
spring:
  application:
    name: sadek
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka%7D}
#      http://user:password@url/eureka
security:
  user:
    password: ${eureka.password}
---
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: 80
    prefer-ip-address: true
    app-group-name: fgsc
    appname: sadek
  password: ${USER_PASSWORD:password}
#security:
#  user:
#    password: ${eureka.password}